DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  start_date TIMESTAMP DEFAULT now() NOT NULL
);

INSERT INTO users (first_name, last_name, email, password)
VALUES
  ('Demo', 'User', 'demo_user@demo.com', '$2a$12$z0JfoVsHbStvoGKLhUe6u.HPyK/LEweXFfDAhnn7YeFrBocl40sbi'),
  ('Darth', 'Vader', 'darthvader@demo.com', '$2a$12$lHK6LVpc15/ZROZcKU00QeiD.RyYq5dVlV/9m4kKYbGibkRc5l4Ne'),
  ('Darth', 'Maul', 'darthmaul@demo.com', '$2a$12$VQ5HgWm34QQK2rJyLc0lmu59cy2jcZiV6U1.bE8rBBnC9VxDf/YQO'),
  ('Luke', 'Skywalker', 'lwalker@demo.com', '$2a$12$2fv9OPgM07xGnhDbyL6xsuAeQjAYpZx/3V2dnu0XNIR27gTeiK2gK'),
  ('The', 'Mandalorian', 'the_man@demo.com', '$2a$12$2fv9OPgM07xGnhDbyL6xsuAeQjAYpZx/3V2dnu0XNIR27gTeiK2gK');