DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_title TEXT NOT NULL,
  post_content TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  owner INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

INSERT INTO posts (post_title, post_content, owner)
VALUES
  ('Post 1', 'What ever', '5'),
  ('Post 2', 'What ever', '4'),
  ('Post 3', 'What ever', '3'),
  ('Post 4', 'What ever', '2'),
  ('Post 5', 'What ever', '1');